### ISSUE TITLE
Does not work with GHE?

### ISSUE THREAD

**Issue by herder** [plan3/stoneboard#31]
I might be configuring this wrong, but I can't get it to work it GHE:
- github.foo.com authenticates ok, but gives a 404 when trying to show the milestones
- api.github.foo.com does not work due to certificate issues
- github.foo.com/api/v3 gives an authorization error.

**Comment by kristiany** [comment]
Ping @ashpool

**Comment by mateusz-fiolka** [comment]
@herder Which env variable are you setting?

**Comment by ashpool** [comment]
I haven't configured Stoneboard in production, but have these settings in my `.env` when running the code locally:
```
GITHUB_CLIENT_ID=5...64e
GITHUB_CLIENT_SECRET=9f...22
CALLBACK_URL=http://127.0.0.1:5000/auth/callback
REPOSITORIES=ashpool/stoneboard-test
GITHUB_HOSTNAME=github.com
JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=16000
```
Perhaps @chids or @hnrc knows how to configure this properly for githubenterprisy?

**Comment by ashpool** [comment]
@herder how do you plan to deploy Stoneboard - on premises or cloudy?

**Comment by herder** [comment]
Turns out I needed to set ```REPOSITORIES``` to ```ab/issues``` instead of ```issues```.
And there's also a bug when receiving a Milestone with no description, but I fixed that. Pico-PR coming up! :)

**Comment by hnrc** [comment]
Closeable? :)

**Comment by herder** [comment]
Yep :)
